apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        
        image: ghcr.io/herrifunix/vitalsync-backend:latest 
        ports:
        - containerPort: 3000
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        
        - name: PGHOST
          value: "database"
        - name: PGUSER
          value: "vitalsync"
        - name: PGDATABASE
          value: "vitalsync_db"
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10